server:
  port: 8888
spring:
  application:
    name: zull-proxy
  boot:    admin:      client:        url: http://localhost:9999
  cloud:
    consul:
      discovery:
        serviceName: zull-proxy
        register: true
      host: 127.0.0.1
      port: 8500